NYPL-Simplified/library_registry

geography_loader.py
model.py
tests/test_geography_loader.py
tests/test_model.py
tests/test_scripts.py

This branch completes the import of data from geojson-places-us by adding a PlaceAlias class which contains alternate names for places.
I don't expect to be using PlaceAlias.language very soon, but I want it in place from the beginning. I think it will be useful for libraries in countries that have more than one official language, like Canada and South Africa.
The other big change here is I added `Place.geo`, which casts the `Place.geography` field to `Geography`. 
Our ORM defines the field as a Geography field, but internally the data is stored as though it were a Geometry field. Without the cast, this means database functions treat places as shapes on a flat plane of undetermined dimensions, rather than shapes on the Earth with distances measured in meters.
I was not able to find any …

Add the PlaceAlias table

---

model.py
tests/test_model.py

This branch creates the concept of "library alias", which is almost exactly the same as "place alias", but for libraries. It's used to create alternate names for libraries (e.g. "NYPL" for the New York Public Library).
This branch also implements `Library.by_name`, which performs a slightly fuzzy match against a library's official name, and a less fuzzy match against its aliases.

Create `LibraryAlias` and implement basic search by library name

---

tests/test_util.py
util.py

This tiny branch uses the python-geoip-geolite2 database and library to turn IP addresses into geographic points representing approximate latitude and longitude.

Added code that turns an IP address into a geometric point.

---

model.py
opds.py
requirements.txt
testing.py
tests/test_model.py
tests/test_opds.py

This branch adds some fields to the `libraries` table which we want to use in OPDS feeds, and implements the ability to turn a list of libraries into an OPDS navigation feed. The OPDS generation code is copied from  LS core. I also copied the idea of an `Annotator`, which will be used when I start writing the app server to insert links to the search interface, and any other app-server-specific information.

Add initial OPDS support

---

bin/add_library
bin/search
bin/search_places
model.py
scripts.py
tests/test_scripts.py

This branch creates three useful command-line scripts:
1. `search_places` lets you search for places by name and find their `external_id`s.
2. `add_library` lets you create a `Library` object and associate a number of `external_id`s with its service area.
3. `search` is a command-line interface to the library search algorithm.
With these three scripts along with `load_places`, I was able to verify that the search algorithm performs reasonably well in a dev environment that includes one library and every place in the United States. I created a library representing NYPL and was able to quickly check whether or not a query ("10018", "Kew Gardens", "Brooklyn", "Kings", "New York") matched a place name inside NYPL's service area.

Add some command-line scripts

---

adobe_vendor_id.py
config.py
model.py
tests/test_adobe_vendor_id.py
util/xmlparser.py

This branch copies all the remaining Adobe vendor ID code that can be copied in from circulation without modification. This includes the code that parses incoming requests, handles the abstract logic of the Vendor ID spec, and generates responses.
It does not include any code that interacts with the data model or the web application -- that code needs to be ported to the new model/application and simplified, and I'll handle it in the next branch.
One bit of code has been modified: the code that gathers Configuration values for the vendor ID implementation. There's almost no code now that most of the configuration information is kept in `Library` objects; all we need to keep track of now are two scalar values: the vendor ID itself and the node value.

Copy adobe vendor ID code

---

app.py
util/flask_util.py

This branch solves the problem we see on a library registry deployed behind a load balancer, where geolocation fails because we look at the load balancer's IP instead of the patron's IP.
As a bonus, this makes it possible to test geolocation locally, by passing in X-Forwarded-For with the IP you want to test.

If the request was forwarded, use the originating IP instead of the IP of the forwarding machine.

---

model.py
tests/test_model.py

I landed my previous branch prematurely. The same problem that caused duplicate entries in `Library.nearby()` was present in the other two `Library` search methods. This branch fixes those methods in the same way, and modifies a test to make sure the problem will break tests if it recurs.

Fix duplicate libraries from showing up in other contexts

---

adobe_vendor_id.py
config.py
controller.py
scripts.py
tests/test_adobe_vendor_id.py

This branch makes it possible for a library registry to take any standard or authdata credentials it doesn't understand and ask another Vendor ID server to validate them. This gives us a migration path for moving from another Vendor ID server to the library registry.

Delegate unrecognized authentication attempts to another Vendor ID server

---

app.py
bin/configuration/configure_integration
bin/configuration/configure_site_setting
bin/configuration/show_integrations
config.py
controller.py
model.py
scripts.py
tests/test_adobe_vendor_id.py
tests/test_model.py
tests/test_scripts.py

I mostly copied and pasted code from the multi-tenant branch of server_core and removed things that aren't relevant here or aren't needed yet. That includes the url, username, and password properties on ExternalIntegration, the list of sitewide settings in config.py, and the function to reload the site configuration. The one thing I left out that might be needed is the settings relationship on Library. It broke a bunch of queries and I wasn't sure if we really needed to get all the settings for a Library, or we'd be mostly looking them up one at a time.
I converted Adobe vendor ID and the sitewide base URL to be read from the db instead of the config file. I didn't bother with a migration since this isn't in production yet.

Brought over ExternalIntegration and ConfigurationSetting from server_core.

---

authentication_document.py
tests/test_authentication_document.py

This branch introduces the `AuthenticationDocument` class, which represents the result of parsing an Authentication For OPDS document (with our extensions). JSON coverage objects are parsed into Place objects, links are extracted, etc.
I noticed two problems when looking at the Authentication for OPDS documents we currently serve. First, we send the name of the library as `name` rather than `title`. Second, we don't send the `type` field. Instead, we send `providers`, which is either an old name for what is now called `type` or is something slightly different--at any rate, I think it's not compliant with the current spec. I'll investigate this more later.

Auth document parser

---

.travis.yml
controller.py
model.py
opds.py
tests/test_controller.py
tests/test_opds.py
util/app_server.py

This branch changes the library registry to use [OPDS 2](https://github.com/opds-community/opds-revision/blob/master/opds-2.0.md), with a custom "catalogs" collection role. Within "catalogs", the metadata and navigation collection are the same as in the overall OPDS 2 spec.
The register endpoint also returns an OPDS catalog now, but it doesn't have a self link yet.

Converted controllers to return OPDS 2 catalogs.

---

controller.py
model.py
requirements.txt
scripts.py
testing.py
tests/test_adobe_vendor_id.py
tests/test_controller.py
tests/test_model.py
tests/test_scripts.py
tests/test_short_client_token.py

This branch implements the shared secret and short name part of #24.
If the OPDS auth document has a public key, the register response will include a short name and shared secret in the library metadata. The shared secret is encrypted and base 64-encoded. A new secret will be generated if one doesn't exist yet or if the request includes the old secret. For now, the short name is generated randomly, and never changes once it exists.
I also renamed Library.adobe_short_name and Library.adobe_shared_secret since they could potentially be used for non-Adobe things, and I added the registry's vendor id to the metadata of its main OPDS catalog.

Generate a short name and shared secret if the library has a public key.

---

authentication_document.py
controller.py
model.py
opds.py
requirements.txt
testing.py
tests/test_authentication_document.py
tests/test_controller.py
tests/test_model.py
tests/test_opds.py

This branch converts the registration controller method to parse the OPDS auth document with AuthenticationDocument, and adds support for registering service areas and logo links.
AuthenticationDocument.parse_coverage wasn't working with the Place class, so I had to refactor it a bit and make MockPlace more like Place.

Use auth document

---

controller.py
model.py
testing.py
tests/test_controller.py
tests/test_model.py

This branch adds `Library.status`, which lets us track an OPDS server's state in the lifecycle from initial registration, to approval (or rejection) by a library registry admin, to going live and showing up in OPDS clients such as SimplyE.
This is in support of https://github.com/NYPL-Simplified/library_registry/issues/25, though it doesn't complete it. We still only have one feed, which contains the 'live' libraries. We need a feed that contains the 'approved' libraries, so that people at those libraries can use real OPDS clients to test out their systems.

Add library status

---

app.py
controller.py
opds.py
tests/test_controller.py
tests/test_opds.py

This branch introduces an alternate feed at /qa which shows only items in the "approved" stage. (The default feed shows only items in the "live" stage.) This is done with alternate inputs into the `nearby` and `search` controllers.

Create a 'qa' feed (as distinct from the 'live' feed) containing only items in the 'approved' stage.

---

authentication_document.py
controller.py
model.py
tests/test_authentication_document.py
tests/test_controller.py

This branch introduces the concept of 'focus area' by adding a `type` field to ServiceArea. The type of ServiceArea we've been dealing with up to this point has `type="eligibility"`, and the new type has `type="focus"`.
A Library advertises its focus area by naming specific places in its Authentication For OPDS document.  I refactored some code from the controller into `AuthenticationDocument` and made it work both for `service_area` and `focus_area`.
Any ServiceArea indicates that people in a certain Place are served by the Library, but the "focus area" indicates a Place that is the Library's primary concern. By default, a Library's focus area is the same as its service area.
We should be prepared for a library to have the same Place as two different ServiceAreas with different types, …

Introduce different types of ServiceArea, such as 'focus area'

---

authentication_document.py
controller.py
model.py
tests/test_authentication_document.py
tests/test_controller.py

This branch closes out https://github.com/NYPL-Simplified/library_registry/issues/39 by storing the last two pieces of information we need from the authentication document: whether anonymous access is allowed and whether you can get library credentials through an entirely online process.

Store booleans for 'anonymous access' and 'online registration'

---

authentication_document.py
tests/test_authentication_document.py
tests/test_controller.py

This branch changes the library registry to handle the near-final Authentication for OPDS format. The main changes:
* Rather than a list of authentication types and a single set of authentication configuration, an auth document has a list of authentication objects, each of which has a `type` as well as its own configuration.
* An authentication document has a list of links, with `rel` as an attribute within each link, rather than an object with `rel` values keyed to sub-lists of links. An authentication flow can have its own list of links, which is separate from the main list.

Expect New OPDS auth format

---

model.py
tests/test_short_client_token.py
util/short_client_token.py

This fixes https://github.com/NYPL-Simplified/circulation/issues/648 by shaving several characters off the 'username' portion of the short client token.

Compare SCTs with low-numbered expiration dates against a new epoch.

---

model.py
tests/test_short_client_token.py

This was the only problem I found when testing the library registry's ability to delegate Adobe ID checks to some other server.

Don't choke when unable to decode the password portion of a Short Client Token.

---

authentication_document.py
bin/set_coverage_area
scripts.py
testing.py
tests/test_authentication_document.py
tests/test_scripts.py

This branch introduces a script for setting a library's service area and focus area. We can use this script to set this information on a per-library basis until we develop a service area editor as part of the circulation manager admin interface.
I refactored a lot of the area-parsing code in `authentication_document.py` so I could call it outside the context of a full authentication document, and moved `MockPlace` into `testing.py` since it's now needed in multiple testing modules.

Script that sets a library's coverage area

---

.travis.yml
app.py
authentication_document.py
config.py
controller.py
model.py
problem_details.py
tests/test_controller.py
util/app_server.py
util/problem_detail.py

This branch makes the registration endpoint for a library registry respond to GET as well as POST. A GET request will give an OPDS 2 catalog containing (at most) one link. This link is a `data:` link describing the terms of service for the registration endpoint. This is as opposed to the catalog endpoints, which  don't have any special terms of service, because their users are random library patrons who don't even know they're using a separate service. But in theory, there could be a different TOS for the registry as a whole.
The circulation manager will retrieve the registration TOS and require a would-be registrar to agree to it before proceeding.
Since this is the first library registry branch in nearly a year, I had to make a number of changes to make sure the code worked and the …

Serve terms of service as part of a document that describes the registration process

---

controller.py
problem_details.py
tests/test_controller.py

This branch addresses https://jira.nypl.org/browse/SIMPLY-467. Registrations will only succeed if a `contact` email address is provided along with the registration request, and the library's Authentication For OPDS includes an email address for patron support and an email address for the designated copyright agent.
Currently the email addresses are not stored anywhere and nothing is done with them -- they just have to be present at the time the library is registered.

Reject registration requests that don't include the three required email addresses

---

controller.py
model.py
tests/test_controller.py
tests/test_model.py

This branch grabs the email addresses that come in associated with a library (the patron support address, the copyright designated agent address, and the configuration contact address) and stores them in a new table called Hyperlink. This is a lot simpler than the Hyperlink table in server_core but it's the same idea -- it's a URL (href) that has a specific relationship (rel) to a library.
Although a library may have multiple links of a given type, we only store one Hyperlink of a given type for a given library. The library's links may change over time, but we try to keep using the same value as long as that is a possibility.

Store incoming email addresses associated with a library

---

app.py
controller.py
model.py
tests/test_controller.py
tests/test_model.py

This branch adds a data model class called Validation, used to keep track of the validation of an email address. Validating an email address requires presenting a secret key to a new controller. Eventually we'll send out emails containing links to that controller.
To avoid the need to validate the same email address over and over again (e.g. because a consortium with 30 libraries uses the same address for their patron support and their integration support), I split out Hyperlink into two classes: Hyperlink and Resource. This setup is more like what we have in the server core: Resource talks about the URI and Hyperlink is just a join table between the URI and the Library. Once the Resource is validated, it's validated for everyone.
The downside of this is that a rogue library can claim …

Create a way to track the validation of an email address

---

app.py
controller.py
emailer.py
model.py
tests/test_controller.py
tests/test_model.py

This completes https://jira.nypl.org/browse/SIMPLY-1007. Confirmation and notification emails will now be sent out appropriately from a properly configured library registry.

Send out validation emails on registration

---

controller.py
model.py
opds.py
tests/test_controller.py
tests/test_opds.py

This branch addresses https://jira.nypl.org/browse/SIMPLY-468. The OPDS catalog for a library will include links to email addresses that have a confirmation step, with information about where they are in the confirmation process.
I use https://schema.org/reservationStatus and https://schema.org/ReservationStatusType to talk about the process, rather than making up my own vocabulary, since the email confirmation process is equivalent to the process of confirming a reservation.
This branch also removes (by commenting out) the requirement that the `contact` email address be provided on initial registration. Because of the strategy we've chosen to phase out Accounts.json, we need to support an interim period where circulation managers that haven't been upgraded to send `contact` can register …

Explain verification status of registered email addresses in a library's OPDS catalog

---

bin/configuration/vendor_id
config.py
controller.py
scripts.py
tests/test_adobe_vendor_id.py
tests/test_scripts.py

I thought I could use the general configuration script for this, but it's complicated enough that I started writing a specialized script specifically for vendor ID, so I figured I might as well test it and put it into the product.

Wrote and tested a script that makes it easy to configure vendor ID.

---

adobe_vendor_id.py
model.py
tests/test_adobe_vendor_id.py
tests/test_short_client_token.py

Currently the AdobeVendorIDModel is responsible for keeping track of delegate servers. When it's asked to do a standard_lookup or an authdata_lookup, it asks the delegate servers first, and if they have an answer, it sends that answer to the client without doing anything else.
This leads to the race condition mentioned in https://jira.nypl.org/browse/SIMPLY-1047, which could cause people to lose their Adobe IDs as we change from having NYPL's circulation manager handle Adobe IDs, to having the library registry do it.
This branch gives responsibility for the delegate servers to the ShortClientTokenDecoder. When we're asked to decode a short client token, we ask the delegate servers to decode it first, and decode it ourselves if that doesn't work. Either way, we create a …

Create local DelegatedIdentifier objects for Adobe IDs obtained from delegate servers

---

controller.py
model.py
tests/test_controller.py
tests/test_model.py

This branch addresses https://jira.nypl.org/browse/SIMPLY-1057, which isn't as bad as I thought when I started the work. But the duplicate check will be really useful.

Generate a wider variety of library short names, and add a duplicate check.

---

model.py
tests/test_adobe_vendor_id.py
tests/test_short_client_token.py

This appears to be the only change necessary to get the library registry responding correctly to realistic HTTP requests of the type made by Adobe's SDK (and Adobe's developers during certification).
This change is necessary to get `authdata_lookup` to give the appropriate error when the authdata is not provided -- it catches ValueError, so `token is None` needs to cause a ValueError. Checking `| in token` was causing a `TypeError`, which wasn't caught.

Raise a ValueError when asked to decode an empty token 

---

controller.py
problem_details.py
testing.py
tests/test_controller.py

This partially addresses https://jira.nypl.org/browse/SIMPLY-1031. There will also be a circulation branch that starts sending the shared secret as part of registration.

Allow registration to change an existing library's authentication_url if the registration form submission included the library's shared secret

---

app.py
controller.py
tests/test_controller.py

This branch fixes a number of problems with the email confirmation workflow, all of them located in untested routing code.
* The `confirm_resource` function took the wrong arguments.
* It referred to a `LibraryRegistry.validation_controller` object, but that object was not instantiated during startup.
* It called the method `ValidationController.validate` when the actual name of the method is `confirm`.
I've done an end-to-end test locally to make sure there are no more problems with this process.

Fix the confirmation workflow, which was broken in several places.

---

controller.py
testing.py

We talked about this a while ago but I never committed it. I didn't end up needing to change any tests - `url` was already getting set and everything still worked.

Changed final_url back to url (final_url only worked in tests).

---

model.py
testing.py
tests/test_controller.py
tests/test_model.py

Currently `Place.lookup_inside` uses comparison of shapefiles to look up a place inside another place (such as California within the United States, or Kern County within California, or 93203 within Kern County). This is very powerful but it also has big problems.
* It's very slow.
* It fails in common cases. It can't parse "New York, New York" because it can't tell whether the first "New York" is referring to New York City or New York State. It can't parse "Santa Barbara, CA" because California has both a city and a county called Santa Barbara. (In real life, anyone wanting to refer to the county would say "Santa Barbara County, CA".)
* Most of the power is for cases that no real person would use. We wouldn't say "93203, Kern County, California", because "93203" is unambiguous on its own. …

Speed up and improve reliability for Place.lookup_inside

---

authentication_document.py
config.py
model.py
testing.py
tests/test_authentication_document.py
tests/test_model.py

According to https://github.com/NYPL-Simplified/Simplified/wiki/Authentication-For-OPDS-Extensions#service_area, a place name like "San Francisco, CA" is invalid. But for the vast majority of libraries, that's the simplest way to represent the library's service area.
I made up that format and I can change the spec a bit (and probably will) to make things easier for people, but I can't change the fact that "San Francisco, CA" doesn't explicitly say which _country_ we're talking about. I don't want to add US-centric bits to the spec, but the vast majority of the people using NYPL's library registry will be in the US, and it would be nice to make things easier for them.
So, this branch allows a library registry to define a 'default nation'. If a coverage area comes in and it doesn't mention …

Allow registries to define a default nation which is used when processing incoming place names that don't mention one

---

app.py
controller.py
model.py
testing.py
tests/test_controller.py
tests/test_model.py

This branch adds a controller that takes place names (or, more generally, coverage areas as defined by https://github.com/NYPL-Simplified/Simplified/wiki/Authentication-For-OPDS-Extensions#service_area), parses them, and returns the corresponding GeoJSON objects. Eventually this can be used by the circulation manager to help admins graphically visualize their service areas. This will help them troubleshoot and it will also tell them when we can't identify a coverage area from a place name.
For now, I intend to use this myself when grandfathering in the coverage areas of the libraries already in the registry.
This is work towards https://jira.nypl.org/browse/SIMPLY-1044.

Make it easy to interactively turn place names into GeoJSON objects

---

app.py
app_helpers.py
controller.py
opds.py
tests/test_app.py
tests/test_controller.py
tests/test_opds.py

This branch adds links to a library's OPDS catalog which let a client grab GeoJSON representations of its focus area and eligibility area. This can be used either by a circulation manager's admin interface ("did I get the service area right?") or by a mobile or web client ("is this my local library?")
I added two controllers which take a library UUID as their input, so rather than copy the code in the existing `library` controller (for looking up a specific library's catalog entry), I wrote the equivalent of the `has_library` function we use in the circulation manager.
Unlike that `has_library`, though, this one is testable, because I created a factory function which takes an app server as an argument and generates a `has_library` implementation for that app server.

Advertise each library's focus and eligibility areas in its catalog entry

---

scripts.py
tests/test_scripts.py

This branch improves the SetCoverageAreaScript.
* Changes to the database are now actually committed.
* Many more strings are now acceptable as coverage documents, and the script now handles all of them.
* You can run the script with no options other than a library name to see the current coverage areas for that library.

Improve set_coverage_area

---

authentication_document.py
tests/test_authentication_document.py

We're going to go through a period where most library service areas are grandfathered in on the library registry side. While this is happening (and even afterwards) we don't want the library registration process to remove coverage areas just because the library's authentication document doesn't provide anything. The lack of information signifies a lack of knowledge on the circ manager's part, not an assertion that a library has no coverage area.
This branch changes `AuthenticationDocument.set_service_areas` to do nothing when no input is provided. I also add a little general coverage of that method, which up to this point has only been tested indirectly.

Handle the case where we know a library's service areas and the library doesn't

---

app.py
app_helpers.py
controller.py
tests/test_app.py
tests/test_controller.py
tests/test_util.py
util/__init__.py

This branch defines a new annotator called `uses_location`. A routing function annotated with `uses_location` should take an argument called `_location`. The app server will make its best guess at the user's location and pass in that Point as `_location`.
This has two benefits:
* You can put `_location=latitude,longitude` in any request to simulate a request from that point. If incoming `_location` is specified in the request, `uses_location` will use that point instead of trying to figure it out from the IP address. This lets us simulate a request from anywhere when testing.
* Location-aware controllers now take a Point as input rather than an IP address, making them easier to test.

It's now possible to simulate a request from anywhere by passing in latitude/longitude coordinates.

---

controller.py
tests/test_controller.py
util/http.py

This branch resolves https://jira.nypl.org/browse/SIMPLY-1395.
The changes to http.py are caused by simply copying in a new copy of https://github.com/NYPL-Simplified/server_core/blob/master/util/http.py. I used this to add some debugging to make it easier to go back and forth with people who are having trouble completing their registrations.

Only reset the shared secret if the library asked for it to be reset.

---

controller.py
package.json
tests/test_controller.py

Sorts information about a library into categories before sending it to the front end (so that the interface can more easily organize the information in a user-friendly way).

Categorize libraryinfo

---

controller.py
package.json
tests/test_controller.py

This change is just to improve the performance on the front end; it makes the library info update itself in a more visually smooth way after an email address is validated.  Goes with https://github.com/NYPL-Simplified/registry_admin/pull/9, which resolves https://jira.nypl.org/browse/SIMPLY-1725.

Return library details on validate email

---

config.py
controller.py
tests/test_controller.py

This fixes https://jira.nypl.org/browse/SIMPLY-1744.
Since the ToS hasn't been deployed or finalized yet, there's no migration. But it's now way too big to include inline.
The circ manager doesn't yet pick up this data (that's https://jira.nypl.org/browse/SIMPLY-467), so there's no circ change either.

Store the ToS link as a hyperlink, not as the actual text of the ToS.

---

app.py
controller.py
tests/test_controller.py

Fixes [SIMPLY-1775](https://jira.nypl.org/browse/SIMPLY-1775).

Endpoint to return all libraries not in a cancelled stage in OPDS format

---

model.py
tests/test_model.py

This is a support branch for https://jira.nypl.org/browse/SIMPLY-1845. It stops an unhandled exception when `Place.lookup_one_through_external_source` is asked to find a place inside a Canadian province.
Right now `lookup_one_through_external_source` only knows one way of finding places: using the `uszipcode` library. Obviously Canadian provinces aren't in its `search.state_to_city_mapper` dictionary, and trying to look up a province abbreviation in that dictionary causes the exception.
Instead of crashing, `lookup_one_through_external_source` now does nothing in this case, since the one trick it knows about won't work.

Don't crash if uszipcode is asked to try to find a place that's not in the US.

---

app.py
controller.py
tests/test_controller.py

Server-side work for [the new registry_admin search feature](https://jira.nypl.org/browse/SIMPLY-1887), which enables admins to search for a library by name.

Add endpoint for admins to search for a library by name

---

config.py
controller.py
tests/test_controller.py

This branch addresses https://jira.nypl.org/browse/SIMPLY-2277. The registry terms of service can be expressed as a simple link, as before, and/or as a snippet of explanatory HTML.

Allow TOS to be stored as a small snippet of HTML in addition to a simple link.

---

controller.py
model.py
tests/test_controller.py
tests/test_model.py

Resolves https://jira.nypl.org/browse/SIMPLY-2348.  (Generating the data for each library, rather than running the query to list all the identifiers, turned out to be a lot easier for getting the information to the front end in a useful format.)

Tell the front end how many Adobe IDs are associated with each library

---

controller.py
tests/test_controller.py

Partially resolves https://jira.nypl.org/browse/SIMPLY-2349.  (I think the proposed changes to the admin endpoint can be mostly handled on the front end, so that will be a separate ticket and PR.)

Filter out cancelled libraries in libraries_opds

---

controller.py
tests/test_controller.py

This branch adds a quick and dirty internal cache for the big list of libraries, hopefully dramatically decreasing the time it takes to process the flood of requests to /libraries and /libraries/qa. We're taking other steps on the client side to reduce the number of requests; this is just a first step.

Cache library lists internally

---

app.py
app_helpers.py
tests/test_app.py

This branch adds compression support to the /libraries and /libraries/qa endpoints if the client requests them using the Accept-Encoding header. The library list compresses from 2.6 megs to 1.9 megs, a 25% improvement. According to @twaddington, the Android HTTP client sends `Accept-Encoding: gzip` by default, so we'll start seeing benefits immediately.
This fixes https://jira.nypl.org/browse/SIMPLY-1778. I talk about a lot of other stuff in that ticket, but it's now covered in other tickets.

Send compressed library lists if the client supports it.

---

opds.py
tests/test_opds.py

This branch formalizes a hotfix I had to put into place on production as part of my work on https://jira.nypl.org/browse/SIMPLY-2664.
The code I had works fine if `libraries` is a list, but in real life, `libraries` is a SQLAlchemy query, and you get the size of a SQLAlchemy query with count(), not len()
I'm a little concerned about the performance effects once `libraries` becomes a much more complicated query involving geographic proximity, but there's also going to be a `LIMIT` attached to those queries, so we'll know how big they can get ahead of time. Also, once we're able to use those queries, there will effectively be no 'large' OPDS feeds and we can get rid of this whole thing.

Add some tests.

---

app.py
controller.py
opds.py
tests/test_controller.py
tests/test_opds.py

This branch addresses https://jira.nypl.org/browse/SIMPLY-2703. The goal is to buy time for the client-side "onboarding" work by promoting libraries near a patron's current location (to help people in the common case), while still showing a big alphabetical library list (since there is no search functionality to help in the uncommon case).
Since different patrons now get different library feeds, I had to remove the caching code. While doing this I discovered that the caching code didn't actually do much, because I'd added it to the controller used by the admin interface (libraries), not the controller used by the mobile clients (libraries_opds). 
I also discovered some significant performance problems building the library feed, caused by having to go to the database to get the contact …

Promote nearby libraries to the top of the alphabetical list
